// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgrmzhykxkvyqwhrqias.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpncm16aHlreGt2eXF3aHJxaWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Nzc1NjAsImV4cCI6MjA2MzI1MzU2MH0.JrQcJHI6JVzASs8w7yFKXdHU51VuHmSLuPnc6tEWXmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);